---
title: "03.1. Data Analysis with Built-In Function - Numerical and Statistical"
output: html_notebook
---

## Built In Function

** Numeric functions **

```{r}
#Round number
round(3.456, digits = 2)
```

```{r}
#Find length of vector
a <- c(1, 3, 5, 7, 9, 11)
length(a)
```

```{r}
#Find length of vector b

b <- c(2, 3, 5, 7, 11, 13, 17)
length(b)

```


```{r}
#absolute value
abs(-5)
```

```{r}
b <- c(-1, 2, 4, -6)
abs(b)
```

```{r}
#square root
sqrt(3)
```

```{r}
sqrt(abs(b))
```

```{r}
ceiling(8.234)
```

```{r}
ceiling(8.99)
```

```{r}
floor(8.234)
```

```{r}
floor(8.99)
```

```{r}
log(10)
```

```{r}
log10(10)
```

```{r}
exp(1)
```


** Statistical functions **

```{r}
a <- 1:10
a
```


```{r}
#Find mean of vector
mean(a)
```

```{r}
#Find standard deviation
sd(a)
```

```{r}
median(a)
```

```{r}
#Sum of all elements in vector
sum(a)
```

Use square bracket [ ] to index vector
```{r}
#Sum of some elements in vector
sum(a[1:5])
```

min, max, pmin, pmax
```{r}
x <- 1:5
y <- c(10, 9 ,8, 1, 2)
max(x)
```

```{r}
min(y)
```

compare vectors element-wise
```{r}
pmin(x, y)
```

```{r}
pmax(x, y)
```

```{r}
max(x, y)
```

